---
- name: Run proxy
  community.docker.docker_container:
    name: httpd
    image: "{{ dockerhub_user }}/tp-devops-httpd:latest"
    pull: always
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "80:80"                     # seul conteneur exposé à l'extérieur
    networks:
      - name: "{{ docker_network_name }}"
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python
